baseURL: https://gaston.life/
enableGitInfo: true
enableRobotsTXT: true

params:
  toc: true

taxonomies:
  tag: tags

markup:
  highlight:
    style: solarized-light

related:
  threshold: 80
  includeNewer: true
  toLower: true
  indices:
  - name: tags
    weight: 100
  - name: date
    pattern: 200601
    width: 50
