baseURL: https://gaston.life/

taxonomies:
  category: categories

related:
  threshold: 80
  includeNewer: true
  toLower: true
  indices:
  - name: categories
    weight: 100
  - name: date
    pattern: 200601
    width: 50
