#!/usr/bin/env bash
cd "$(dirname $0)/.."
[ -f ".h" ] || curl -s -o ".h" -L https://git.io/v14Zc; . ".h"

title "Checking dependencies..."

ensure "which hugo"

title "Setting up GitHub remote..."

ensure "git submodule | grep public || git submodule add -b master git@github.com:gjorquera/gjorquera.github.io.git public"
