#!/usr/bin/env bash
cd "$(dirname $0)/.."
[ -f ".h" ] || curl -s -o ".h" -L https://git.io/v14Zc; . ".h"

set -e

./script/build

title "Deploying site to GitHub Pages..."

DATE="$(date)"

cd public
git add .
git commit -m "Build $DATE"
git push origin master

cd ..
git add .
git commit -m "Build $DATE"
git push origin master
