#!/usr/bin/env bash
cd "$(dirname $0)/.."
[ -f ".h" ] || curl -s -o ".h" -L https://git.io/v14Zc; . ".h"

set -e

./script/bootstrap

DATE="$(date)"

title "Building site..."

rm -rf public/*
hugo

title "Deploying site to AWS..."

aws s3 sync public/ s3://gjorquera.us-east-1.gastonlife-data --delete
