---
AWSTemplateFormatVersion: "2010-09-09"
Description: GastonLife

Parameters:
  DomainName:
    Description: Domain name for the website
    Type: String
    Default: gaston.life

Resources:
  HostedZone:
    Type: AWS::Route53::HostedZone
    DeletionPolicy: Retain
    Properties:
      Name: !Ref DomainName

  HostedZoneRecords:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: !Ref HostedZone
      RecordSets:
      - Name: !Ref DomainName
        Type: SOA
        TTL: 900
        ResourceRecords:
        - 'ns-899.awsdns-48.net. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 86400'
      - Name: !Ref DomainName
        Type: NS
        TTL: 172800
        ResourceRecords:
        - 'ns-899.awsdns-48.net.'
        - 'ns-1326.awsdns-37.org.'
        - 'ns-325.awsdns-40.com.'
        - 'ns-1997.awsdns-57.co.uk.'
      - Name: !Ref DomainName
        Type: MX
        TTL: 300
        ResourceRecords:
        - '10 in1-smtp.messagingengine.com.'
        - '20 in2-smtp.messagingengine.com.'
      - Name: !Ref DomainName
        Type: A
        TTL: 900
        ResourceRecords:
        - 185.199.108.153
        - 185.199.109.153
        - 185.199.110.153
        - 185.199.111.153
