---
AWSTemplateFormatVersion: "2010-09-09"
Description: GastonLife

Parameters:
  DomainName:
    Description: Domain name for the website
    Type: String
    Default: gaston.life

Resources:
  HostedZone:
    Type: AWS::Route53::HostedZone
    DeletionPolicy: Retain
    Properties:
      Name: !Ref DomainName

  HostedZoneRecords:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: !Ref HostedZone
      RecordSets:
      - Name: !Ref DomainName
        Type: SOA
        TTL: 900
        ResourceRecords:
        - 'ns-899.awsdns-48.net. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 86400'
      - Name: !Ref DomainName
        Type: NS
        TTL: 172800
        ResourceRecords:
        - 'ns-899.awsdns-48.net.'
        - 'ns-1326.awsdns-37.org.'
        - 'ns-325.awsdns-40.com.'
        - 'ns-1997.awsdns-57.co.uk.'
      - Name: !Ref DomainName
        Type: MX
        TTL: 300
        ResourceRecords:
        - '10 in1-smtp.messagingengine.com.'
        - '20 in2-smtp.messagingengine.com.'
      - Name: !Ref DomainName
        Type: A
        AliasTarget:
          HostedZoneId: Z2FDTNDATAQYW2
          DNSName: !GetAtt SiteCDN.DomainName
      - Name: !Ref DomainName
        Type: AAAA
        AliasTarget:
          HostedZoneId: Z2FDTNDATAQYW2
          DNSName: !GetAtt SiteCDN.DomainName

  SiteCert:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DomainName
      DomainValidationOptions:
      - DomainName: !Ref DomainName
        ValidationDomain: !Ref DomainName

  SiteCDN:
    Type: AWS::CloudFront::Distribution
    DependsOn:
    - SiteBucket
    Properties:
      DistributionConfig:
        Origins:
        - DomainName: !Sub ${SiteBucket}.s3-website-us-east-1.amazonaws.com
          Id: OnlyOrigin
          CustomOriginConfig:
            HTTPPort: '80'
            HTTPSPort: '443'
            OriginProtocolPolicy: http-only
        Enabled: true
        IPV6Enabled: true
        Aliases:
        - !Ref DomainName
        DefaultCacheBehavior:
          Compress: true
          DefaultTTL: 300
          TargetOriginId: OnlyOrigin
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https
        PriceClass: PriceClass_100
        ViewerCertificate:
          AcmCertificateArn: !Ref SiteCert
          SslSupportMethod: sni-only
        Logging:
          Bucket: !GetAtt LogsBucket.RegionalDomainName

  SiteBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: 'gjorquera.us-east-1.gastonlife-data'
      AccessControl: 'PublicRead'
      WebsiteConfiguration:
        IndexDocument: 'index.html'
        ErrorDocument: '404.html'

  SiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref SiteBucket
      PolicyDocument:
        Statement:
          - Action: 's3:GetObject'
            Effect: 'Allow'
            Principal: '*'
            Resource: !Sub 'arn:aws:s3:::${SiteBucket}/*'

  LogsBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: 'Retain'
    Properties:
      BucketName: 'gjorquera.us-east-1.gastonlife-logs'
